### ISSUE TITLE
grunt coverage is not working with latest devDependencies

### ISSUE THREAD

**Issue by mic0331** [AndrewKeig/advanced-express-application-development#2]
Hello,

I'm currently working on chapter 2 of your book.

When i use last version of the `devDependencies`, the coverage.html page is not working, I do have a blank html page when i run `grunt coverage`

```
"devDependencies": {
    "supertest": "~0.8.3",
    "grunt": "~0.4.2",
    "grunt-cafe-mocha": "~0.1.10",
    "grunt-jscoverage": "0.0.3",
    "grunt-env": "~0.4.1",
    "mocha": "~1.17.0"
  }
```

Do you have a solution to this issue ?

Thanks

**Comment by AndrewKeig** [comment]
Hey; apologies for the late response.

Can you uninstall jscoverage and instead install it from npm.

npm install -g jscoverage

Please do let me know how you get on.
