### ISSUE TITLE
Chapter 2 Tests failing with TypeError: Cannot call method 'drop' of undefined

### ISSUE THREAD

**Issue by alsoicode** [AndrewKeig/advanced-express-application-development#4]
Following the code samples up to page 24, my project.js test file...

```
var app = require('../app'),
    request = require('supertest'),
    assert = require('assert'),
    mongoose = require('mongoose'),
    login = require('./login');

describe('Vision Project API', function() {
    var id;

    beforeEach(function(done) {
        mongoose.connection.collections['projects'].drop(function(err) {

            var proj = {
                name: "test name",
                user: login.user,
                token: login.token,
                repositories: ["node-plates"]
            };

            mongoose.connection.collections['projects'].insert(proj, function(err, docs) {
                id = docs[0]._id;
                done();
            });
        });
    });

    describe("When creating a new resource /project", function() {
        var project = {
            name: "New Project",
            user: login.user,
            token: login.token,
            repositories: ["12345", "9898"]
        };

        it("should responsd with 201", function(done) {
            request(app).post("/project").send(project).expect("Content-Type", /json/).expect(201).end(function(err, res) {
                var proj = JSON.parse(res.text);
                assert.equal(proj.name, project.name);
                assert.equal(proj.user, login.user);
                assert.equal(proj.token, login.token);
                assert.equal(proj.repositories[0], project.repositories[0]);
                assert.equal(proj.repositories[1], project.repositories[1]);
                assert.equal(res.header['location'], '/project/' + proj._id);
                done();
            });
        });
    });
});
```

Results in:

```
1) Vision Project API "before each" hook:
 TypeError: Cannot call method 'drop' of undefined
  at Context.<anonymous> (/home/btaylor/node-projects/vision/test/project.js:11:53)
  at Hook.Runnable.run (/usr/lib/node_modules/mocha/lib/runnable.js:204:15)
  at next (/usr/lib/node_modules/mocha/lib/runner.js:263:10)
  at Object._onImmediate (/usr/lib/node_modules/mocha/lib/runner.js:280:5)
  at processImmediate [as _immediateCallback] (timers.js:330:15)
```

MongoDB is running, and the "vision" database exists...what am I doing wrong?

Thanks,
Brandon

**Comment by AndrewKeig** [comment]
Hey 

Apologies for not responding sooner; I have been up against it on support this week :)  Lets see if we can get you up and running.

Seems to be working ok for me; it looks like the collection does not exist; as mongoose.connection.collections['projects'] is returning undefined.. 

You shouldn't be seeing this error if mongo is running correctly. 

Can you run the following; from terminal:

mongo
use vision
show collections

You could also install robomongo; and have a look around; make sure the vision project exists.

Can you also check your db connection; you should have 'mongodb://localhost/vision' in configuration.  You could try changing this to 127.0.0.1; you may have an issue with localhost.

Also check which process is using that port:

lsof -i:27017

Let me know how you get on.

**Comment by alsoicode** [comment]
I'm running Linux Mint 16 with Node v0.10.25, and installed Mongodb using the built-in software manager. I downloaded RoboMongo and am able to connect and execute functions against Mongo. The database "vision" exists, and I can show collections.

I used RoboMongo to create the "projects" collection just to see if the beforeEach method would drop a collection that previously existed, but I'm still getting the same error. Switching the config to use 127.0.0.1 also results in the same error.

If I run:

```
moch test
```

Against Chapter 2 from the Github repo, it works as expected. I'm sure it's something I've done, but I'm not exactly sure what to look for. I'm primarily a Python developer and just getting my feet wet with the Node ecosystem.

A triple-check inspection of my code isn't turning up any differences in structure or syntax up to page 24 of the book. I'm more than happy to create a public repo and drop my code in it for you. Thanks for helping!

**Comment by AndrewKeig** [comment]
That would be great.

**Comment by alsoicode** [comment]
Repo is at: https://github.com/alsoicode/vision

**Comment by AndrewKeig** [comment]
Hey 

If you look at page 26 you will see you are missing the following from your ./lib/express.js file.

The models are assigned to mongoose from inside ../routes/project in the accompanying service.

Hope this resolves things; let us know.

var express = require('express')
, http = require('http')
, config = require('../configuration')
, db = require('../db')
, heartbeat = require('../routes/heartbeat')
, project = require('../routes/project')
, notFound = require('../middleware/notFound') 
, app = express();

app.use(express.bodyParser());
app.set('port', config.get('express:port')); 
app.use(express.logger({ immediate: true, format: 'dev' })); 
app.get('/heartbeat', heartbeat.index);
app.post('/project', project.post);
app.use(notFound.index);
http.createServer(app).listen(app.get('port'));
module.exports = app;

**Comment by alsoicode** [comment]
Thanks Andrew. Looks like I was just missing the post route, and I was premature in running my tests.
