### ISSUE TITLE
Trouble "Authorising App" in Chapter 5 page 93.

### ISSUE THREAD

**Issue by ghost** [AndrewKeig/advanced-express-application-development#5]
First indication, Cucumber tests fail at 'Then I should see my name and logout link'.

Logged in to app and clicked "Authorize Application" button. Returns straight back to home page.

Built chapter 5 code from this repo - same thing.

Without getting bogged down in researching the ins and outs of OAuth, is there any quick fix to get this working?

Many thanks in advance.

**Comment by AndrewKeig** [comment]
Hey; are you logged in to GitHub and have you authorised the application in GitHub?

Please make sure settings/applications/developer applications in GitHub is setup correctly.

You should have : 

If you have setup SSL
Application name : vision
Homepage URL : https://127.0.0.1:8443
Authorization callback URL : https://127.0.0.1:8443

If you have NOT setup SSL
Application name : vision
Homepage URL : https://127.0.0.1:3000
Authorization callback URL : https://127.0.0.1:3000

Your config file should includes ./config/development.json; 3000 will be 8443 if you have setup SSL.

"auth": {
    "homepage": "https://127.0.0.1:3000"
  , "callback": "https://127.0.0.1:3000/auth/github/callback"
  , "clientId": "FROM_DEVELOPER_APPLICATIONS_PAGE"
  , "clientSecret": "FROM_DEVELOPER_APPLICATIONS_PAGE"
  },
