### ISSUE TITLE
Question not issue

### ISSUE THREAD

**Issue by xaevir** [AndrewKeig/advanced-express-application-development#7]
Hello I'm using your book to write my first advanced app so I'm excited. My question is: For the project  schema, why do you not set the the 'name' attribute as unique? Instead you check for the existence of 'name' by calling projectSchema.findOne before calling either project.save or project.update. Is there a reason why you do no want this validation check in the model?  If there is a better place to ask questions than github I am sorry for not knowing.

update: 
The question could also apply to your check in the post and put routes where you use the String module to check for empty 'name' values instead relying on the model's validation 
 ex. if (S(req.body.name).isEmpty() ) return res.json(400, 'Bad Request');

So what if I added to the model that I want 'name' to not be over 10 chars. Would you continue to check for this in the routes or would you suggest using the mongoose's validation error?

thank you kindly.

**Comment by AndrewKeig** [comment]
Hi, thanks for the question; its a good one; I was never really happy with the solution I used for validation; Hapi solves the problem better with validation blocks.. 

Basically I want to return the correct HTTP response with error messages from a REST perspective; (although I have not made this obvious from the book :).   So if you attempt to save a model with a unique index; and don't check if the name is already used; it will throw an error (I think); so you would probably need to catch that error and respond accordingly with the correct REST code and error message.  Trying to test those endpoints is problematic; as you need to rebuild the index; which can cause mixed results; the test may fail if the index is not built quickly enough;  this is not ideal. Not a fan of this approach.

If you can make it work using this method in a clean way go for it, if you are happy to catch errors.  I would also suggest you take a look at a module https://github.com/AndrewKeig/express-validation I have put together which solves the validation problem in a cleaner way; this will allow you to get rid of String module; its a middleware that uses Hapis validation library https://github.com/spumko/joi; joi provides a much better way of doing validation: 

https://github.com/AndrewKeig/express-validation
