### ISSUE TITLE
Discrepancies between the book and the repo

### ISSUE THREAD

**Issue by rodrigo-medeiros** [AndrewKeig/advanced-express-application-development#9]
I don't know if here is the right place to report this, but here it goes:

On chapter 2, _Feature: List issues_, I see that the code here in the repo is very different (and makes a lot more sense, by the way) from the same code from the book, in the method `Project.prototype.issues`, in the file `lib/project/index.js`.

In the book, I have:
  exports.issues = function (req, res) {
    logger.info('Request' + req.url);

```
ProjectSchema.findOne({_id: req.params.id}, function (error, project) {
  if (error) return res.json(500, 'Internal Server Error');
  if (project == null) return res.json(404, 'Page Not Found'):

  var git = GitHubRepo(project.token, project.user);

  git.issues(project.repositories, function (error, response) {
    if (error) return res.json(500, 'Internal Server Error');
    return res.json(200, response);
  });
});
```

  };

Are you planning correcting that and update the book? I bought the book from Amazon, and I haven't received any sort of update, so I'm not sure if you already corrected that.

**Comment by AndrewKeig** [comment]
Hey

Many thanks for spotting this; and sorry for the late response.

You are right it should be :

```
Project.prototype.issues = function(id, callback){
```

instead of:

```
exports.issues = function (req, res) {
logger.info('Request' + req.url);
```

If you like you can submit errata here; click the support tab:

http://www.packtpub.com/advanced-express-web-application-development/book

I will ok it.

Thanks
